#define USB_SUSPEND_WAKEUP_DELAY 0
#define FIRMWARE_VERSION u8"GLeeV/D3Maq"
#define RAW_USAGE_PAGE 0xFF60
#define RAW_USAGE_ID 0x61
#define LAYER_STATE_8BIT

#define UNICODE_SELECTED_MODES UNICODE_MODE_WINDOWS

#define RGB_MATRIX_STARTUP_SPD 60